### ISSUE TITLE
Message : There is a dialogue box open in another browser window. You must close that dialogue box or sign out.

### ISSUE THREAD

**Issue by kine** [NAVDEMO/RunTests#7]
There is sometime this error when running the tests during development (from VSCode through powershell):

```
Running c:\git\MSDyn365BC_AppTemplate\TestApp\..\Scripts\Settings.ps1 ...
Running tests in container through navcontainerhelper...
  Codeunit XXXXXX Blablabla Failure (0.393 seconds)
Message : There is a dialogue box open in another browser window. You must close that dialogue box or sign out.
ClientSession in Error
At C:\ProgramData\NavContainerHelper\Extensions\BC\PsTestTool\ClientContext.ps1
:94 char:17
+                 throw "ClientSession in Error"
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (ClientSession in Error:String
   ) [], RuntimeException
    + FullyQualifiedErrorId : ClientSession in Error
```

Seems mainly when there was opened webclient in browser before running the tests.

**Comment by kine** [comment]
Even when I remove all sessions on the service tier, I have same error.

**Comment by kine** [comment]
Yes, this one, because I have multiple codeunits. But It works/worked sometime, because I was able to run the tests before...
![image](https://user-images.githubusercontent.com/110221/53748209-2dc63080-3ea5-11e9-8edc-34425b7b7811.png)

**Comment by freddydk** [comment]
In the code - it run RunSelected - not the Run button.

**Comment by kine** [comment]
Ok, I found the problem... there was another test app, which was removed, but of course, the lines in the test suite were there. Leading to error. When removed, all is ok. It means problem was in data.

Thanks!
